name: Build, test, and publish nightly wheel

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-test-publish-nightly-wheel:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build PyPi Wheel
        id: build-wheel
        uses: neuralmagic/nm-actions/actions/pypi_build@main
        with:
          dev: false
          release: false

      - name: Set Env
        run: |
          pip3 install --upgrade pip && pip3 install --upgrade setuptools
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      
      - name: Fetch name of whl
        run: |
            echo "FILENAME=$(echo dist/*.whl)" >> $GITHUB_ENV
      
      - name: Install whl
        run: |
            pip3 install $FILENAME[dev]
      
      - name: Remove src files and run tests
        run: |
              rm -rf src
              make test
      
      - name: Publish Nightly Wheel
        uses: neuralmagic/nm-actions/actions/publish-whl@main
        with:
          username: ${{ secrets.PYPI_PUBLIC_USER }}
          password: ${{ secrets.PYPI_PUBLIC_AUTH }}
          whl: ./$FILENAME