name: Check Ready Label

on:
  pull_request_target:
    branches: [ main , 'release/*' ]
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ready-label-check:
    runs-on: gcp-k8s-vllm-util
    steps:
      - name: Fail if ready label has not been applied to PR
        if: "!contains(github.event.pull_request.labels.*.name, 'ready')"
        run: |
          echo "::error::The PR is not labeled as 'ready'"
          exit 1

      - name: Succeed if ready label has been applied to PR
        if: contains(github.event.pull_request.labels.*.name, 'ready')
        run: |
          echo "::info::The PR is labeled as 'ready'"
          exit 0
